In [81]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [82]:
df = pd.read_csv('Data Sets/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [84]:
df.shape

(10000, 14)

In [85]:
df.isnull().sum()       # there's no null value in the dataset, no need of data preprocessing

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [86]:
df['Exited'].value_counts()   # 1 -> disabled bank account

Exited
0    7963
1    2037
Name: count, dtype: int64

In [87]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [88]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [89]:
df = df.drop(columns = ['RowNumber', 'CustomerId', 'Surname'])
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [90]:
df = pd.get_dummies(df, columns = ['Geography', 'Gender'], drop_first = True)
df.head()     # Germany -> False, Spain -> False means France -> True
              # Male -> False means Female -> True

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1              False   
1               1        112542.58       0              False   
2               0        113931.57       1              False   
3               0         93826.63       0              False   
4               1         79084.10       0              False   

   Geography_Spain  Gender_Male  
0            False        False  
1             True        False  
2            False        False  
3            False        False  
4             True        False

In [91]:
X = df.drop(columns = ['Exited'])
y = df['Exited']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [92]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 11)
(2000, 11)
(8000,)
(2000,)


DATA SCALING

In [93]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [94]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [95]:
X_test_scaled

array([[-1.03768121,  0.77498705, -1.0482813 , ..., -0.58312392,
        -0.57273139,  0.91509065],
       [ 0.30708683, -0.46686456, -0.70174202, ..., -0.58312392,
        -0.57273139,  0.91509065],
       [-1.23422423,  0.29735181, -1.0482813 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       ...,
       [-0.86182692, -0.46686456,  1.72403288, ..., -0.58312392,
         1.74601919,  0.91509065],
       [-0.30323097, -0.84897275, -1.0482813 , ...,  1.71490137,
        -0.57273139, -1.09278791],
       [ 0.04847759,  1.25262228,  1.3774936 , ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [96]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [97]:
model = Sequential()

model.add(Dense(3, activation = 'sigmoid', input_dim = 11))    # no of nodes (perceptron) = 3, total inputs = 11
model.add(Dense(1, activation = 'sigmoid'))       # output layer    

# (11 x 3) + 3 = 36    (3 x 1) + 1 = 4
# total 40
#  O
#  O   O
#  O

C:\Users\Anindya Dolui\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [98]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [101]:
model.compile(loss = 'binary_crossentropy', optimizer = 'Adam')     # log loss function not summation

In [102]:
model.fit(X_train_scaled, y_train, epochs = 10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 986us/step - loss: 0.4470
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - loss: 0.4373
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - loss: 0.4332
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - loss: 0.4308
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4375  
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - loss: 0.4279
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - loss: 0.4238
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - loss: 0.4230
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - loss: 0.4197
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - loss: 0.4230


In [104]:
model.layers[0].get_weights()

[array([[ 0.17908977, -0.00808408,  0.1045995 ],
        [-1.7525113 ,  0.60657334, -2.5838573 ],
        [ 0.00616533, -0.0169602 ,  0.02748887],
        [-0.3319503 ,  0.27782393, -0.27983916],
        [ 0.02286491, -0.05521136,  0.07537749],
        [ 0.21196738, -0.12831995, -0.10611844],
        [ 0.04739   , -1.4275324 ,  0.5229107 ],
        [-0.03233706,  0.1476438 ,  0.03021857],
        [ 0.01283297,  1.1126182 , -0.40609556],
        [-0.09968951,  0.11725217,  0.07932834],
        [ 0.32970792, -0.4817243 ,  0.47050756]], dtype=float32),
 array([-0.3003532, -0.7173256,  0.745502 ], dtype=float32)]

In [105]:
model.layers[1].get_weights()

[array([[-0.54602146],
        [ 1.2076681 ],
        [-1.7086568 ]], dtype=float32),
 array([-0.7889325], dtype=float32)]

In [109]:
y_log = model.predict(X_test_scaled)     # sigmoid gives a probability between 0 and 1
y_log

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step


array([[0.14332451],
       [0.10765701],
       [0.1305294 ],
       ...,
       [0.05884114],
       [0.10793788],
       [0.4273951 ]], dtype=float32)

In [111]:
y_pred = np.where(y_log>0.5, 1, 0)  # setting a thresold as 0.5, returns 1 where the value is > 0.5 otherwise 0
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [114]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
ac    # the model is 82.3% accurate

0.823